---
###################################################################
#Proyecto     : Sistema de Gestión Ansible
#Descripción  : Playbook Pruebas OPM
#Compañia     : CITI Value In Real Time 
#Cliente      : OPM
#Autor        : Víctor Manuel Pérez Ramírez
#Correo       : victor.perez@citi.com.mx
###################################################################

- name: Estatus WS_Transfer
  hosts: all
  become: yes
  vars_files:
    - variables/main.yml
  #ignore_errors: yes
  gather_facts: no
  tasks:
    - name: Estatus WS_Transfer
      shell: "{{ Componente.WS_Transfer.Estatus }}"
      register: comando
      failed_when: "'No esta ejecutando el proceso' in comando.stdout"
    - debug: msg="{{ comando.stdout_lines }}"
  tags:
    - never
    - Estatus_General
    - Estatus_Transfer
    - Estatus_WS_Transfer
    - Estatus_WS_ALL
...