---
###################################################################
#Proyecto     : Sistema de Gestión Ansible
#Descripción  : Playbook Pruebas OPM
#Compañia     : CITI Value In Real Time 
#Cliente      : OPM
#Autor        : Víctor Manuel Pérez Ramírez
#Correo       : victor.perez@citi.com.mx
###################################################################

- name: Estatus WS_Transfer
  hosts: all
  become: yes
  vars_files:
    - variables/main.yml
  #ignore_errors: yes
  gather_facts: no
  tasks:
    - name: Estatus WS_Transfer
      shell: "{{ Componente.WS_Transfer.Estatus }}"
      register: comando
      failed_when: "{{ Componente.WS_Transfer.Estatus }} in comando.stdout"
    - debug: msg="{{ comando.stdout_lines }}"
  tags:
    - never
    - Estatus_General
    - Estatus_Transfer
    - Estatus_WS_Transfer
    - Estatus_WS_ALL

- name: Encendido WS_Transfer
  hosts: all
  become: yes
  vars_files:
    - variables/main.yml
  #ignore_errors: yes
  gather_facts: no
  tasks:
    - name: Encendido WS_Transfer
      shell: "{{ Componente.WS_Transfer.Encendido }}"
      register: comando
      failed_when: "{{ Componente.WS_Transfer.Estatus }} in comando.stdout"
    - debug: msg="{{ comando.stdout_lines }}"
  tags:
    - never
    - Encendido_General
    - Encendido_Transfer
    - Encendido_WS_Transfer
    - Encendido_WS_ALL

- name: Apagado WS_Transfer
  hosts: all
  become: yes
  vars_files:
    - variables/main.yml
  #ignore_errors: yes
  gather_facts: no
  tasks:
    - name: Apagado WS_Transfer
      shell: "{{ Componente.WS_Transfer.Apagado }}"
      register: comando
      failed_when: "{{ Componente.WS_Transfer.Estatus }} in comando.stdout"
    - debug: msg="{{ comando.stdout_lines }}"
  tags:
    - never
    - Apagado_General
    - Apagado_Transfer
    - Apagado_WS_Transfer
    - Apagado_WS_ALL

- name: Restart WS_Transfer
  hosts: all
  become: yes
  vars_files:
    - variables/main.yml
  #ignore_errors: yes
  gather_facts: no
  tasks:
    - name: Restart WS_Transfer
      shell: "{{ Componente.WS_Transfer.Restart }}"
      register: comando
      failed_when: "{{ Componente.WS_Transfer.Estatus }} in comando.stdout"
    - debug: msg="{{ comando.stdout_lines }}"
  tags:
    - never
    - Restart_General
    - Restart_Transfer
    - Restart_WS_Transfer
    - Restart_WS_ALL
...